services:
  hanzi-learn:
    build: .
    image: hanzi-learn:latest
    container_name: hanzi-learn
    platform: linux/amd64
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./env:/app/env:ro
      - ./data:/app/data
